package com.example.JinWei.imagetransferqr;

import android.content.Intent;
import android.graphics.Bitmap;
import android.provider.MediaStore;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.ValueEventListener;
import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import static com.example.JinWei.imagetransferqr.MainActivity.mFirebaseDatabase;


public class DownloadActivity extends AppCompatActivity {

    private TextView txtResultCode;
    private ImageView imageView;
    private LinearLayout layout;

    private DatabaseReference mImageQrDatabaseReference;
    private BitmapConverter converter;
    private Bitmap imageBitmap;
    private int imageSize;
    private String childKey = "";


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_download);

        converter = new BitmapConverter();
        imageView = (ImageView) findViewById(R.id.imageView);
        txtResultCode = (TextView) findViewById(R.id.txtResultCode);
        layout = (LinearLayout) findViewById(R.id.linearLayout);

        IntentIntegrator integrator = new IntentIntegrator(DownloadActivity.this);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt("Scan");
        integrator.setCameraId(0);
        integrator.setBeepEnabled(false);
        integrator.setBarcodeImageEnabled(false);
        integrator.initiateScan();

    }

    public void btnSave(View view) {

        MediaStore.Images.Media.insertImage(getContentResolver(), imageBitmap, childKey , "Generated by ImageTransfer QR");  // Saves the image.
        Toast.makeText(this, "Image saved to camera roll", Toast.LENGTH_SHORT).show();

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if(result != null) {
            if(result.getContents() == null) {
                Log.e("Scan*******", "Cancelled scan");

            } else {
                imageSize = layout.getWidth() - 150;
                childKey = result.getContents();
                txtResultCode.setText(childKey);
                getImageFromDatabase();
            }
        } else {
            super.onActivityResult(requestCode, resultCode, data);
        }
    }

    private String getImageFromDatabase(){
        mImageQrDatabaseReference = mFirebaseDatabase.getReference().child("qrMessage").child(childKey).child("imageString");
        mImageQrDatabaseReference.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                String imageString = dataSnapshot.getValue(String.class);
                imageBitmap = converter.stringToBitmap(imageString);
                imageView.setImageBitmap(Bitmap.createScaledBitmap(imageBitmap, imageSize, imageSize, false));

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });

        return null;
    }



}
